### ISSUE TITLE
Cannot find module nodegit.node

### ISSUE THREAD

**Issue by steadystatic** [Glavin001/GitLab-Pages#34]
This is on CentOS 6. Saw previous issues and tried those recommendations (deleting node_modules and npm). Permissions are all properly set. Scratching my head:

[autodeploy@GIT GitLab-Pages]$ DEBUG=\* npm start

> GitLab-Pages@0.1.0 start /home/autodeploy/GitLab-Pages
> node ./bin/www

  express:router:route new / +0ms
  express:router:layer new / +1ms
  express:router:route get / +2ms
  express:router:layer new / +0ms
  express:router:route new /login +0ms
  express:router:layer new /login +0ms
  express:router:route post /login +0ms
  express:router:layer new / +0ms
  express:router:route new /logout +0ms
  express:router:layer new /logout +0ms
  express:router:route get /logout +0ms
  express:router:layer new / +0ms
  express:router:route new / +1ms
  express:router:layer new / +0ms
  express:router:route get / +0ms
  express:router:layer new / +0ms
  express:router:route new /:project_id/enable +0ms
  express:router:layer new /:project_id/enable +0ms
  express:router:route get /:project_id/enable +1ms
  express:router:layer new / +0ms
  express:router:route new /:project_id/disable +0ms
  express:router:layer new /:project_id/disable +0ms
  express:router:route get /:project_id/disable +0ms
  express:router:layer new / +0ms

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/autodeploy/GitLab-Pages/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! not ok code 0
[autodeploy@GIT GitLab-Pages]$ node -v
v0.10.42
[autodeploy@GIT GitLab-Pages]$ npm -v
1.3.6

**Comment by ryan-shaw** [comment]
You may need to run a Node version of v0.12 or greater
